import {
  UserAccount,
  SubscriptionTier,
  PayOSTransaction,
  AuditLogItem,
  ServiceHealth,
  KpiSummary,
  RevenueMetric,
} from "@/types/admin";

export const MOCK_KPIS: KpiSummary = {
  mrr: 184500000, // 184.5M VND
  mrrGrowth: 16.4,
  totalUsers: 24580,
  usersGrowth: 12.8,
  activeSubscriptions: 3420,
  subGrowth: 18.2,
  todayMomentsShared: 148920,
  todayActiveWidgets: 68450,
  paymentSuccessRate: 99.6,
  todayTransactions: 86,
  todayRevenue: 28500000,
  servicesUpCount: 5,
  servicesTotal: 5,
};

export const MOCK_TIERS: SubscriptionTier[] = [
  {
    id: "tier-free",
    name: "LocCoc Cơ Bản (Starter)",
    code: "FREE",
    description: "Dành cho người dùng mới bắt đầu kết nối bạn thân và ghim widget",
    priceMonthly: 0,
    priceYearly: 0,
    durationDays: 30,
    limits: {
      maxFriends: 10,
      maxMomentsPerDay: 20,
      maxVideoSeconds: 5,
      cloudStorageGb: 1,
      historyDays: 30,
    },
    features: [
      "Ghim tối đa 10 bạn bè thân thiết",
      "Gửi 20 khoảnh khắc ảnh/ngày",
      "Video tối đa 5 giây",
      "Lưu trữ lịch sử 30 ngày gần nhất",
      "Widget cơ bản trên màn hình chính",
    ],
    isActive: true,
    subscribersCount: 21160,
    monthlyRevenue: 0,
    updatedAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "tier-gold",
    name: "LocCoc Gold (Bạn Thân VIP)",
    code: "GOLD",
    description: "Mở rộng vòng bạn bè không giới hạn, gửi video dài và lưu trữ vĩnh viễn",
    priceMonthly: 49000,
    priceYearly: 490000,
    durationDays: 30,
    limits: {
      maxFriends: 100,
      maxMomentsPerDay: -1, // Không giới hạn
      maxVideoSeconds: 15,
      cloudStorageGb: 20,
      historyDays: -1, // Vĩnh viễn
    },
    features: [
      "Kết nối tối đa 100 bạn bè",
      "Gửi khoảnh khắc không giới hạn mỗi ngày",
      "Quay video khoảnh khắc dài 15 giây",
      "Lưu trữ album kỷ niệm vĩnh viễn (Cloud 20GB)",
      "Tải ảnh chất lượng cao gốc (HD)",
      "Huy hiệu ngôi sao vàng (Gold Star Badge)",
      "Widget màn hình khóa (Lock Screen Widget)",
    ],
    isActive: true,
    isPopular: true,
    subscribersCount: 2850,
    monthlyRevenue: 139650000,
    updatedAt: "2026-03-15T10:30:00Z",
  },
  {
    id: "tier-plus",
    name: "LocCoc Plus / VIP Creator",
    code: "PLUS",
    description: "Đặc quyền tối thượng cho nhà sáng tạo nội dung và nhóm bạn lớn",
    priceMonthly: 89000,
    priceYearly: 890000,
    durationDays: 30,
    limits: {
      maxFriends: -1, // Không giới hạn
      maxMomentsPerDay: -1,
      maxVideoSeconds: 30,
      cloudStorageGb: 100,
      historyDays: -1,
    },
    features: [
      "Không giới hạn số lượng bạn bè",
      "Quay video siêu dài 30 giây kèm âm nhạc",
      "Tùy biến icon ứng dụng & giao diện cá nhân hóa",
      "Xóa watermark LocCoc khi chia sẻ ra Story",
      "Bộ lọc màu độc quyền (Exclusive Vintage & Film Filters)",
      "Huy hiệu VIP Creator phát sáng trên Widget",
      "Hỗ trợ kỹ thuật ưu tiên 24/7",
    ],
    isActive: true,
    subscribersCount: 570,
    monthlyRevenue: 50730000,
    updatedAt: "2026-04-01T09:15:00Z",
  },
];

export const MOCK_USERS: UserAccount[] = [
  {
    id: "usr-01",
    email: "ducthinh.admin@loccoc.vn",
    username: "@ducthinh",
    fullName: "Đức Thịnh",
    phoneNumber: "0908123456",
    role: "ADMIN",
    status: "ACTIVE",
    currentTierCode: "PLUS",
    currentTierName: "LocCoc Plus VIP",
    friendsCount: 158,
    momentsCount: 1420,
    widgetsCount: 4,
    totalSpent: 890000,
    createdAt: "2025-11-10T09:00:00Z",
    lastActiveAt: "2026-10-06T10:15:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=DucThinhLocCoc",
  },
  {
    id: "usr-02",
    email: "minhtran.photo@gmail.com",
    username: "@minh.lens",
    fullName: "Trần Nhật Minh",
    phoneNumber: "0912345678",
    role: "CREATOR",
    status: "ACTIVE",
    currentTierCode: "GOLD",
    currentTierName: "LocCoc Gold",
    friendsCount: 84,
    momentsCount: 890,
    widgetsCount: 3,
    totalSpent: 490000,
    createdAt: "2026-01-15T14:20:00Z",
    lastActiveAt: "2026-10-06T09:45:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=MinhLens",
  },
  {
    id: "usr-03",
    email: "ngan.cute@gmail.com",
    username: "@ngan.dethuong",
    fullName: "Trần Kim Ngân",
    phoneNumber: "0987654321",
    role: "USER",
    status: "ACTIVE",
    currentTierCode: "GOLD",
    currentTierName: "LocCoc Gold",
    friendsCount: 42,
    momentsCount: 650,
    widgetsCount: 2,
    totalSpent: 147000,
    createdAt: "2026-02-01T11:00:00Z",
    lastActiveAt: "2026-10-06T08:30:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=NganCute",
  },
  {
    id: "usr-04",
    email: "quanghai.vlogger@saigon.vn",
    username: "@quanghai.daily",
    fullName: "Phạm Quang Hải",
    phoneNumber: "0933445566",
    role: "CREATOR",
    status: "ACTIVE",
    currentTierCode: "PLUS",
    currentTierName: "LocCoc Plus VIP",
    friendsCount: 450,
    momentsCount: 3200,
    widgetsCount: 5,
    totalSpent: 890000,
    createdAt: "2026-02-18T16:40:00Z",
    lastActiveAt: "2026-10-06T07:10:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=HaiVlog",
  },
  {
    id: "usr-05",
    email: "thuytrang.student@ctu.edu.vn",
    username: "@trang.vo",
    fullName: "Võ Thụy Trang",
    phoneNumber: "0977889900",
    role: "USER",
    status: "ACTIVE",
    currentTierCode: "FREE",
    currentTierName: "LocCoc Starter",
    friendsCount: 9,
    momentsCount: 115,
    widgetsCount: 1,
    totalSpent: 0,
    createdAt: "2026-03-05T08:12:00Z",
    lastActiveAt: "2026-10-05T22:00:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=TrangStudent",
  },
  {
    id: "usr-06",
    email: "spammer.bot@tempmail.com",
    username: "@spambot99",
    fullName: "Bot Quảng Cáo Rác",
    phoneNumber: "0999000111",
    role: "USER",
    status: "BANNED",
    currentTierCode: "FREE",
    currentTierName: "LocCoc Starter",
    friendsCount: 1,
    momentsCount: 4,
    widgetsCount: 0,
    totalSpent: 0,
    createdAt: "2026-03-20T20:10:00Z",
    lastActiveAt: "2026-03-21T01:00:00Z",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=SpamBot",
  },
];

export const MOCK_TRANSACTIONS: PayOSTransaction[] = [
  {
    id: "tx-88301",
    orderCode: 8830101,
    userId: "usr-02",
    userName: "Trần Nhật Minh (@minh.lens)",
    userEmail: "minhtran.photo@gmail.com",
    tierId: "tier-gold",
    tierName: "LocCoc Gold (1 Năm)",
    amount: 490000,
    status: "PAID",
    description: "Nang cap LocCoc Gold 12 thang",
    paymentLinkId: "plink_88301_vietqr",
    qrCodeUrl: "https://img.vietqr.io/image/970422-loccocpay-compact2.png",
    payOsTransactionId: "pos_tx_9981249",
    createdAt: "2026-10-06T08:30:00Z",
    paidAt: "2026-10-06T08:31:14Z",
    webhookVerified: true,
  },
  {
    id: "tx-88302",
    orderCode: 8830102,
    userId: "usr-04",
    userName: "Phạm Quang Hải (@quanghai.daily)",
    userEmail: "quanghai.vlogger@saigon.vn",
    tierId: "tier-plus",
    tierName: "LocCoc Plus VIP (1 Năm)",
    amount: 890000,
    status: "PAID",
    description: "Gia han LocCoc Plus Creator 2026",
    paymentLinkId: "plink_88302_vietqr",
    qrCodeUrl: "https://img.vietqr.io/image/970422-loccocpay-compact2.png",
    payOsTransactionId: "pos_tx_9981250",
    createdAt: "2026-10-06T07:05:00Z",
    paidAt: "2026-10-06T07:06:22Z",
    webhookVerified: true,
  },
  {
    id: "tx-88303",
    orderCode: 8830103,
    userId: "usr-03",
    userName: "Trần Kim Ngân (@ngan.dethuong)",
    userEmail: "ngan.cute@gmail.com",
    tierId: "tier-gold",
    tierName: "LocCoc Gold (1 Tháng)",
    amount: 49000,
    status: "PAID",
    description: "Thanh toan LocCoc Gold 1 thang",
    paymentLinkId: "plink_88303_vietqr",
    qrCodeUrl: "https://img.vietqr.io/image/970422-loccocpay-compact2.png",
    payOsTransactionId: "pos_tx_9981251",
    createdAt: "2026-10-05T19:25:00Z",
    paidAt: "2026-10-05T19:26:05Z",
    webhookVerified: true,
  },
  {
    id: "tx-88304",
    orderCode: 8830104,
    userId: "usr-07",
    userName: "Đặng Hữu Tài (@huutai)",
    userEmail: "huutai.dev@gmail.com",
    tierId: "tier-gold",
    tierName: "LocCoc Gold (1 Tháng)",
    amount: 49000,
    status: "PENDING",
    description: "Dang cho quet ma VietQR PayOS",
    paymentLinkId: "plink_88304_vietqr",
    qrCodeUrl: "https://img.vietqr.io/image/970422-loccocpay-compact2.png",
    createdAt: "2026-10-06T10:10:00Z",
    webhookVerified: false,
  },
  {
    id: "tx-88305",
    orderCode: 8830105,
    userId: "usr-08",
    userName: "Ngô Bá Khá (@bakha99)",
    userEmail: "bakha.social@yahoo.com",
    tierId: "tier-gold",
    tierName: "LocCoc Gold (1 Tháng)",
    amount: 49000,
    status: "EXPIRED",
    description: "Het thoi han thanh toan 15 phut",
    createdAt: "2026-10-05T14:00:00Z",
    webhookVerified: false,
  },
];

export const MOCK_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: "aud-901",
    actorId: "usr-01",
    actorEmail: "thiennhan.admin@loccoc.vn",
    actorRole: "ADMIN",
    service: "admin-service",
    action: "UPDATE_TIER_PRICING",
    targetEntity: "SubscriptionTier",
    targetId: "tier-gold",
    ipAddress: "118.69.12.84",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0",
    status: "SUCCESS",
    details: { oldPrice: 39000, newPrice: 49000, updatedBy: "thiennhan.admin" },
    createdAt: "2026-10-06T09:45:00Z",
  },
  {
    id: "aud-902",
    actorId: "usr-01",
    actorEmail: "thiennhan.admin@loccoc.vn",
    actorRole: "ADMIN",
    service: "admin-service",
    action: "BAN_USER",
    targetEntity: "UserAccount",
    targetId: "usr-06",
    ipAddress: "118.69.12.84",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0",
    status: "SUCCESS",
    details: { reason: "Spam pornographic/violating moments on Widget", reportCount: 12 },
    createdAt: "2026-10-06T09:12:00Z",
  },
  {
    id: "aud-903",
    actorId: "system-payos",
    actorEmail: "webhook@payos.vn",
    actorRole: "ADMIN",
    service: "payment-service",
    action: "VERIFY_WEBHOOK_HMAC",
    targetEntity: "PayOSTransaction",
    targetId: "tx-88301",
    ipAddress: "103.20.144.5",
    userAgent: "PayOS-Webhook-Delivery/2.0",
    status: "SUCCESS",
    details: { orderCode: 8830101, amount: 490000, verified: true },
    createdAt: "2026-10-06T08:31:15Z",
  },
  {
    id: "aud-904",
    actorId: "usr-02",
    actorEmail: "minhtran.photo@gmail.com",
    actorRole: "CREATOR",
    service: "auth-service",
    action: "LOGIN_SUCCESS",
    targetEntity: "Session",
    targetId: "sess-8891",
    ipAddress: "14.169.55.20",
    userAgent: "LocCoc-FlutterApp/1.4.0 (iOS 18)",
    status: "SUCCESS",
    createdAt: "2026-10-06T08:45:00Z",
  },
];

export const MOCK_SERVICES: ServiceHealth[] = [
  {
    name: "API Gateway (NestJS)",
    port: 3000,
    status: "UP",
    latencyMs: 8,
    uptime: "99.98%",
    version: "1.2.0",
    dbPoolActive: 0,
    dbPoolMax: 0,
    lastChecked: "Vừa xong",
  },
  {
    name: "Auth Service (NestJS)",
    port: 3001,
    status: "UP",
    latencyMs: 14,
    uptime: "99.95%",
    version: "1.1.0",
    dbPoolActive: 6,
    dbPoolMax: 20,
    lastChecked: "Vừa xong",
  },
  {
    name: "User Service (NestJS)",
    port: 3002,
    status: "UP",
    latencyMs: 12,
    uptime: "99.95%",
    version: "1.1.0",
    dbPoolActive: 5,
    dbPoolMax: 20,
    lastChecked: "Vừa xong",
  },
  {
    name: "Payment Service (Spring Boot)",
    port: 8085,
    status: "UP",
    latencyMs: 18,
    uptime: "99.99%",
    version: "3.4.3",
    dbPoolActive: 8,
    dbPoolMax: 30,
    lastChecked: "Vừa xong",
  },
  {
    name: "Admin Service (Spring Boot)",
    port: 8086,
    status: "UP",
    latencyMs: 16,
    uptime: "99.99%",
    version: "3.4.3",
    dbPoolActive: 4,
    dbPoolMax: 30,
    lastChecked: "Vừa xong",
  },
];

export const MOCK_REVENUE_CHART: RevenueMetric[] = [
  { date: "01/10", revenue: 14500000, transactions: 45, newSubscriptions: 28 },
  { date: "02/10", revenue: 19800000, transactions: 62, newSubscriptions: 42 },
  { date: "03/10", revenue: 16200000, transactions: 51, newSubscriptions: 34 },
  { date: "04/10", revenue: 22400000, transactions: 78, newSubscriptions: 56 },
  { date: "05/10", revenue: 31000000, transactions: 99, newSubscriptions: 70 },
  { date: "06/10", revenue: 28500000, transactions: 86, newSubscriptions: 64 },
];
